commit-msg: run sed directly on input
There's no point in running `cat ... | sed` when sed can operate
directly on inputs.

Release-Notes: skip
Change-Id: Ibf026fe8a4ff428599351f3a714613e304d4200e

diff --git a/resources/com/google/gerrit/server/tools/root/hooks/commit-msg b/resources/com/google/gerrit/server/tools/root/hooks/commit-msg
--- a/resources/com/google/gerrit/server/tools/root/hooks/commit-msg
+++ b/resources/com/google/gerrit/server/tools/root/hooks/commit-msg
@@ -56,9 +56,9 @@ dest="$1.tmp.${random}"
 
 trap 'rm -f "$dest" "$dest-2"' EXIT
 
-if ! cat "$1" | sed -e '/>8/q' | git stripspace --strip-comments > "${dest}" ; then
-   echo "cannot strip comments from $1"
-   exit 1
+if ! sed -e '/>8/q' "$1" | git stripspace --strip-comments > "${dest}" ; then
+  echo "cannot strip comments from $1"
+  exit 1
 fi
 
 if test ! -s "${dest}" ; then
