commit-msg: Make sure Change-Id is inserted before Signed-off-by trailers
There is no support in git interpret-trailers to specify any ordering
of a trailer compared to other trailers. However, it is possible to
tell it to put a new trailer before other trailers with the same name.
(Ab)use this to insert the Change-Id trailer as a Signed-off-by
trailer before other Signed-off-by trailers and then use sed to remove
the Signed-off-by: prefix from that specific line.

This does not fully solve issue 12546, but it at least resolves the
most critical part of it.

Bug: 12546
Release-Notes: commit-msg: The Change-Id is now inserted before any Signed-off-by
Change-Id: I55e92790af2a2c855136c21293900904a6a51729

diff --git a/resources/com/google/gerrit/server/tools/root/hooks/commit-msg b/resources/com/google/gerrit/server/tools/root/hooks/commit-msg
--- a/resources/com/google/gerrit/server/tools/root/hooks/commit-msg
+++ b/resources/com/google/gerrit/server/tools/root/hooks/commit-msg
@@ -43,7 +43,7 @@ fi
 random=$({ git var GIT_COMMITTER_IDENT ; echo "$refhash" ; cat "$1"; } | git hash-object --stdin)
 dest="$1.tmp.${random}"
 
-trap 'rm -f "${dest}"' EXIT
+trap 'rm -f "$dest" "$dest-2"' EXIT
 
 if ! git stripspace --strip-comments < "$1" > "${dest}" ; then
    echo "cannot strip comments from $1"
@@ -70,8 +70,24 @@ if git interpret-trailers --parse < "$1" | grep -q "^$token: $pattern$" ; then
   exit 0
 fi
 
+# There must be a Signed-off-by trailer for the code below to work. Insert a
+# sentinel at the end to make sure there is one.
 # Avoid the --in-place option which only appeared in Git 2.8
-if ! git interpret-trailers --trailer "$token: $value" < "$1" > "$dest" ; then
+if ! git interpret-trailers \
+         --trailer "Signed-off-by: SENTINEL" < "$1" > "$dest-2" ; then
+  echo "cannot insert Signed-off-by sentinel line in $1"
+  exit 1
+fi
+
+# Make sure the trailer appears before any Signed-off-by trailers by inserting
+# it as if it was a Signed-off-by trailer and then use sed to remove the
+# Signed-off-by prefix and the Signed-off-by sentinel line.
+# Avoid the --in-place option which only appeared in Git 2.8
+# Avoid the --where option which only appeared in Git 2.15
+if ! git -c trailer.where=before interpret-trailers \
+         --trailer "Signed-off-by: $token: $value" < "$dest-2" |
+     sed -re "s/^Signed-off-by: ($token: )/\1/" \
+         -e "/^Signed-off-by: SENTINEL/d" > "$dest" ; then
   echo "cannot insert $token line in $1"
   exit 1
 fi
