Handle commit messages when verbose commits are used.
Commit messages with "verbose" include a diff and a content marker that must
be ignored during empty checks. Stripspace already knows about the marker,
but comment stripping removes the marker, so the marker must be handled
before comment stripping, otherwise the diff ends up as part of the commit
message.

Change-Id: I63ea4b81e602dcc574ff2054953267a8bfd21500

diff --git a/resources/com/google/gerrit/server/tools/root/hooks/commit-msg b/resources/com/google/gerrit/server/tools/root/hooks/commit-msg
--- a/resources/com/google/gerrit/server/tools/root/hooks/commit-msg
+++ b/resources/com/google/gerrit/server/tools/root/hooks/commit-msg
@@ -33,6 +33,17 @@ dest="$1.tmp.${random}"
 
 trap 'rm -f "${dest}"' EXIT
 
+# If a user has "verbose" commits, then there is a diff after the following
+# marker. In order to assert emptiness, that diff must be pruned before pruning
+# comments:
+GIT_VERBOSE_MARKER="------------------------ >8 ------------------------"
+sed "/${GIT_VERBOSE_MARKER}/q" < "$1" > "${dest}"
+
+if ! mv "${dest}" "$1" ; then
+  echo "cannot mv ${dest} to $1"
+  exit 1
+fi
+
 if ! git stripspace --strip-comments < "$1" > "${dest}" ; then
    echo "cannot strip comments from $1"
    exit 1
