Handle messages with only comments in the commit-msg hook
Commit messages with comments occur when the editor is aborted, and
should be treated as empty.

We do this using git-stripspace, which was introduced in 2005, so this
has no compatibility implications.

Change-Id: I78b50a789860cc11d63d891b0507786890158754

diff --git a/resources/com/google/gerrit/server/tools/root/hooks/commit-msg b/resources/com/google/gerrit/server/tools/root/hooks/commit-msg
--- a/resources/com/google/gerrit/server/tools/root/hooks/commit-msg
+++ b/resources/com/google/gerrit/server/tools/root/hooks/commit-msg
@@ -16,6 +16,12 @@
 # See the License for the specific language governing permissions and
 # limitations under the License.
 
+# $RANDOM will be undefined if not using bash, so don't use set -u
+random=$( (whoami ; hostname ; date; cat $1 ; echo $RANDOM) | git hash-object --stdin)
+dest="$1.tmp.${random}"
+
+trap 'rm -f "$dest"' EXIT
+
 # avoid [[ which is not POSIX sh.
 if test "$#" != 1 ; then
   echo "$0 requires an argument."
@@ -27,17 +33,30 @@ if test ! -f "$1" ; then
   exit 1
 fi
 
-if test ! -s "$1" ; then
+if ! git stripspace --strip-comments < "$1" > "${dest}" ; then
+   echo "cannot strip comments from $1"
+   exit 1
+fi
+
+if test ! -s "${dest}" ; then
   echo "file is empty: $1"
   exit 1
 fi
 
-# $RANDOM will be undefined if not using bash, so don't use set -u
-random=$( (whoami ; hostname ; date; cat $1 ; echo $RANDOM) | git hash-object --stdin)
-dest="$1.tmp.${random}"
+if ! mv ${dest} "$1" ; then
+  echo "cannot mv ${dest} to $1"
+  exit 1
+fi
 
 # Avoid the --in-place option which only appeared in Git 2.8
 # Avoid the --if-exists option which only appeared in Git 2.15
-cat "$1" \
-  | git -c trailer.ifexists=doNothing interpret-trailers --trailer "Change-Id: I${random}" > "${dest}" \
-  && mv "${dest}" "$1"
+if ! git -c trailer.ifexists=doNothing interpret-trailers \
+      --trailer "Change-Id: I${random}" < "$1" > "$dest" ; then
+  echo "cannot insert change-id line in $1"
+  exit 1
+fi
+
+if ! mv ${dest} "$1" ; then
+  echo "cannot mv ${dest} to $1"
+  exit 1
+fi
